Booker/urls.py
from django.urls import path
from . import views

app_name='Booker'
urlpatterns= [
    path('home/', views.startHome, name="booker-home"),
    path('home/<str:pk>/', views.home, name="home"),
    path('booking-request/<str:pk>/', views.bookingRequest, name="booking-request"),
    path('paid-unpaid/<str:pk>/', views.finishPaymentStatus, name="paid-unpaid"),
    path('assign-seat/<str:pk>/', views.assignSeat, name="assign-seat"), 
    path('edit-assigned-seat/<str:pk>/', views.editAssignedSeat, name="edit-assigned-seat"),
    path('manage-payment_info/<str:pk>/', views.managePaymentInformation, name="manage-payment_info"),
    path('add-payment_info/<str:pk>/', views.addPaymentInfo, name="add-payment_info"),
    path('update-payment_info/<str:pk>/', views.updatePaymentInfo, name="update-payment_info"),
    path('delete-payment_info/<str:pk>/', views.deletePaymentInfo, name="delete-payment_info"),
    
]

BusBooking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static 
from django.conf import settings
from django.views.static import serve
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('Customer.urls')),
    path('booker/', include('Booker.urls')),
    path('bus-admin/', include('Bus_admin.urls')), 
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),  
]

urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

Bus_admin/urls.py
from django.urls import path
from . import views

app_name='Bus_admin'
urlpatterns= [
    path('home/', views.startHome, name="bus_admin-home"),
    path('home/<str:pk>/', views.home, name="home"),
    path('manage-single-bus/<str:pk>/', views.manageSingleBus, name="manage-single-bus"),
    path('add-single-bus/<str:pk>/', views.addSingleBus, name="add-single-bus"),
    path('update-single-bus/<str:pk>/', views.updateSingleBus, name="update-single-bus"),
    path('delete-single-bus/<str:pk>/', views.deleteSingleBus, name="delete-single-bus"),

    ##Managing Route urls

    path('add-route/', views.addRoute, name="add-route"),
    path('update-route/<str:pk>/', views.updateRoute, name="update-route"),
    path('add-sub-route/', views.addSubRoute, name="add-sub-route"),
    path('update-sub-route/<str:pk>/', views.updateSubRoute, name="update-sub-route"),
    # path('delete-route/<str:pk>/', views.deleteRoute, name="delete-route"),
    path('delete-sub-route/<str:pk>/', views.deleteSubRoute, name="delete-sub-route"),
]

Bus_admin/models.py
from django.db import models
from django.contrib.auth.models import User
from System_admin.models import Bus
# Create your models here.


class Single_Bus(models.Model):
    bus=models.ForeignKey(Bus, on_delete=models.CASCADE, null=True)
    plate_number=models.CharField(max_length=200, null=True)
    bus_number=models.CharField(max_length=200, null=True)
    bus_type=models.CharField(max_length=200, null=True)
    bus_detail=models.CharField(max_length=200, null=True)
    number_of_seats=models.IntegerField()
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str((self.bus.name, self.bus_number))

class Route(models.Model):
    route_admin=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name=models.CharField(max_length=255, null=True)
    start=models.CharField(max_length=255, null=True)
    destination=models.CharField(max_length=255, null=True)
    via_cities=models.CharField(max_length=255, null=True)
    travel_date=models.DateField(null=True)
    travel_begin_time=models.TimeField(null=True)
    travel_distance=models.IntegerField(null=True)
    travel_aproximate_time=models.CharField(max_length=255, null=True)
    single_seat_price=models.IntegerField(null=True)
    travel_facilities=models.CharField(max_length=255, null=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str(self.name)
     
  

   
"Because every Route may have more than one bus"
    
class SubRoute(models.Model):
    sub_route_admin=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    main_route=models.ForeignKey(Route, on_delete=models.CASCADE, null=True)
    bus=models.ForeignKey(Single_Bus, on_delete=models.SET_NULL, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return str((self.main_route.name, self.bus.bus.name, self.bus.bus_number)) 


# class SubRouteAdmin(models.Model):
#     user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
#     sub_route=models.ForeignKey(SubRoute, on_delete=models.CASCADE, null=True)
    
#     def __str__(self):
#         return (self.user.username)
        

# class SubRouteBusAdmin(models.Model):
#     user=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
#     subroute_bus=models.ManyToManyField(Single_Bus)
    
#     def __str__(self):
#         return (self.user.username)

"""I added this class for seat"""
"You need to add bunch of seat_no (1, 2,3,4,5,6,..."
"Then we will do on how to display seat lists based on a particular bus number of seat"
"Before you go to book please first add seat"
class Seat(models.Model):
    seat_no=models.IntegerField()
    
    def __str__(self):
        return str(self.seat_no) 
    

Bus_admin/forms.py
from django.forms import ModelForm

from .models import Route, SubRoute

    
class RouteForm(ModelForm):
    class Meta:
        model=Route
        fields='__all__'
        

class SubRouteForm(ModelForm):
    class Meta:
        model=SubRoute
        fields='__all__'     
        

Bus_admin/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from Bus_admin.models import Route, Single_Bus, SubRoute
from System_admin.models import Bus, UserType
from django.contrib.auth.decorators import login_required
from .decorators import admin_only
from Customer.decorators import allowed_users
from .forms import RouteForm, SubRouteForm
# Create your views here.

@login_required(login_url='login')
@admin_only
def startHome(request):
    context={}
    return render(request, 'Bus_admin/start_home.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def home(request, pk):
    user=get_object_or_404(User, id=pk)
    buses=user.bus_set.all()
    sub_routes=SubRoute.objects.all()
    routes=user.route_set.all()
    context={'buses':buses, 'routes':routes, 'sub_routes':sub_routes}
    if request.user.user_type.type != 'busadmin':
        return HttpResponse("Not your page!")
    return render(request, 'Bus_admin/home.html', context)

"""Managing single bus"""
@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def manageSingleBus(request, pk):
    bus=get_object_or_404(Bus, id=pk)
    single_buses=bus.single_bus_set.all()
    context={'bus':bus, 'single_buses':single_buses}
    if request.user != bus.bus_admin:
        return HttpResponse("You are not allowed here!")
    return render(request, 'Bus_admin/manage_single_bus.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def addSingleBus(request, pk):
    bus=get_object_or_404(Bus, id=pk)
    if request.method == 'POST':
       singlebus=Single_Bus.objects.create(
          bus=bus,
          plate_number=request.POST['plate_number'], 
          bus_number=request.POST['bus_number'], 
          bus_type=request.POST['bus_type'], 
          bus_detail=request.POST['bus_detail'], 
          number_of_seats=request.POST['number_of_seats'], 
       )
       return redirect('Bus_admin:manage-single-bus', pk=bus.id)
    context={'bus':bus}
    if request.user != bus.bus_admin:
        return HttpResponse("You are not allowed here!")
    return render(request, 'Bus_admin/add_single_bus.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def updateSingleBus(request, pk):
    single_bus=get_object_or_404(Single_Bus, id=pk)
    if request.method == 'POST':
       singlebus=Single_Bus.objects.filter(id=pk).update(
          bus=single_bus.bus,
          plate_number=request.POST['plate_number'], 
          bus_number=request.POST['bus_number'], 
          bus_type=request.POST['bus_type'], 
          bus_detail=request.POST['bus_detail'], 
          number_of_seats=request.POST['number_of_seats'], 
       )
       return redirect('Bus_admin:manage-single-bus', pk=single_bus.bus.id)
    context={'single_bus':single_bus}
    if request.user != single_bus.bus.bus_admin:
        return HttpResponse("You are not allowed here!")
    return render(request, 'Bus_admin/update_single_bus.html', context)
 
@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])   
def deleteSingleBus(request, pk):
    single_bus=get_object_or_404(Single_Bus, id=pk)
    if request.method=='POST':
       single_bus.delete()
       return redirect('Bus_admin:manage-single-bus', pk=single_bus.bus.id)
    if request.user != single_bus.bus.bus_admin: 
           return HttpResponse("You are not allowed here!")
    return render(request, 'Bus_admin/delete.html', {'obj':single_bus})
"""End of single bus management"""

"""Managing Route  and SubRoute"""
@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def addRoute(request):
    form=RouteForm()
    
    if request.method == 'POST':
        form =RouteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Bus_admin:bus_admin-home')
        
    context={'form':form}
    return render(request, 'Bus_admin/route_form.html', context)\
        
@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def updateRoute(request, pk):
    subroute =get_object_or_404(SubRoute, id=pk)
    form =RouteForm(instance=subroute.main_route)
    
    if request.method=='POST':
        form=RouteForm(request.POST, instance=subroute.main_route)
        if form.is_valid():
            form.save()
            return redirect('Bus_admin:bus_admin-home')
        
    context={'form':form}
    if request.user != subroute.bus.bus.bus_admin:
        return HttpResponse("You are not allowed here!")
    return render(request, 'Bus_admin/route_form.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def addSubRoute(request):
    form=SubRouteForm()
    
    if request.method == 'POST':
        form =SubRouteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Bus_admin:bus_admin-home')
        
    context={'form':form}
    return render(request, 'Bus_admin/add_sub_route_form.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def updateSubRoute(request, pk):
    subroute=get_object_or_404(SubRoute, id=pk)
    form =SubRouteForm(instance=subroute)
    
    if request.method=='POST':
        form=SubRouteForm(request.POST, instance=subroute)
        if form.is_valid():
            form.save()
            return redirect('Bus_admin:bus_admin-home')
        
    context={'form':form}
    if request.user != subroute.bus.bus.bus_admin:
        return HttpResponse("You are not allowed here!")
    return render(request, 'Bus_admin/update_sub_route_form.html', context)

# def deleteRoute(request, pk):
#     subroute=get_object_or_404(SubRoute, id=pk)
#     if request.method=='POST':
#         subroute.main_route.delete()
#         return redirect('Bus_admin:home', pk=request.user.id)
#     if request.user != subroute.bus.bus.bus_admin:
#         return HttpResponse("You are not allowed here!")
#     return render(request, 'Booker/delete.html', {'obj':subroute.main_route})

@login_required(login_url='login')
@allowed_users(allowed_roles=['busadmin'])
def deleteSubRoute(request, pk):
    subroute=get_object_or_404(SubRoute, id=pk)
    if request.method=='POST':
        subroute.delete()
        return redirect('Bus_admin:home', pk=request.user.id)
    if request.user != subroute.bus.bus.bus_admin:
        return HttpResponse("You are not allowed here!")
    return render(request, 'Bus_admin/delete.html', {'obj':subroute})

Bus_admin/templates/Bus_admin/add_single_bus.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}
<div>
    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <label for="bus">Bus Brand:</label><br>
            <input type="text" id="bus" name="bus" value="{{bus.name}} " readonly>
        </div>
        <div>
            <label for="plate_number">Bus Plate Number:</label><br>
            <input type="text" id="plate_number" name="plate_number" min="1" required>
        </div>

        <div>
            <label for="bus_number">Bus Number:</label><br>
            <input type="number" id="bus_number" name="bus_number" min="1" required>
        </div>

        <div>
            <label for="bus_type">Bus Type:</label><br>
            <input type="text" id="bus_type" name="bus_type" required>
        </div>
        <div>
            <label for="bus_detail">Bus detail:</label><br>
            <input type="text" id="bus_detail" name="bus_detail" required>
        </div>
        <div>
            <label for="number_of_seats">Number of Seat:</label><br>
            <input type="number" id="number_of_seats" name="number_of_seats" min="1" required>
        </div>



        <input type="submit" value="Save">

    </form>
</div>
{% endblock content%}

Bus_admin/templates/Bus_admin/add_sub_route_form.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}

<div>
    <form method="POST" action="">
        {% csrf_token %} {{form.as_p}}
        <input type="submit" value="Submit">

    </form>
</div>
{% endblock content%}

Bus_admin/templates/Bus_admin/delete.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}
<form method="POST" action="">
    {% csrf_token%}

    <p>Are you sure you want to delete "{{obj}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>

    <input type="submit" value="Confirm">

</form>
{% endblock content%}

Bus_admin/templates/Bus_admin/home.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}

<!-- <p>{{request.user.user_type.type}}</p> -->

<div class="py-4 mx-4">
    <a href="{% url 'Bus_admin:add-route' %}"><button class="btn btn-primary">Add Routes</button></a>


    <a href="{% url 'Bus_admin:add-sub-route'  %}"><button class="btn btn-primary">Add Sub Routes</button></a>

</div>




<div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
    <table class="table dataTable my-0" id="dataTable">
        <thead>
            <tr>
                <th>Subroute Admin</th>
                <th>Traveling Bus</th>
                <th>Traveling Bus Plate & Number</th>
                <th>Main Route</th>
                <th>Start</th>
                <th>Destination </th>
                <th>Via Cities </th>
                <th>Travel Date </th>
                <th>Travel Begin Time </th>
                <th>Travel Distance</th>
                <th>Travel approximate long</th>
                <th>Single seat price</th>
                <th>Travel Facilities</th>
            </tr>
        </thead>
        <tbody>
            {% for sub_route in sub_routes%} {% for bus in buses%} {% if sub_route.bus.bus == bus%}
            <tr>
                <td>{{sub_route.sub_route_admin.username}}</td>
                <td>{{sub_route.bus.bus.name}}</td>
                <td>{{sub_route.bus.plate_number}} - {{sub_route.bus.bus_number}}</td>
                <td>{{sub_route.main_route.name}}</td>
                <td>{{sub_route.main_route.start}}</td>
                <td>{{sub_route.main_route.destination}}</td>
                <td>{{sub_route.main_route.via_cities}}</td>
                <td>{{sub_route.main_route.travel_date}}</td>
                <td>{{sub_route.main_route.travel_begin_time}}</td>
                <td>{{sub_route.main_route.travel_distance}}</td>
                <td>{{sub_route.main_route.travel_aproximate_time}}</td>
                <td>{{sub_route.main_route.single_seat_price}}</td>
                <td>{{sub_route.main_route.travel_facilities}}</td>
                <td><a href="{% url 'Bus_admin:update-sub-route' sub_route.id %}">Update SubRoute</a></td>
                <td><a href="{% url 'Bus_admin:update-route' sub_route.id %}">Update Route</a></td>
                <td>
                    <a href="{% url 'Bus_admin:delete-sub-route' sub_route.id %}" ">DeleteSubRoute</a>
            </td>
        </tr>
        {%endif%} {% endfor %}{% endfor %}

        </tbody>

    </table>
</div>

 {% endblock content%}

Bus_admin/templates/Bus_admin/manage_route.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}
<div>
    {% for subroute in subroutes%}

    <p>{{subroute.main_route.name}}</p>
    {% endfor %}
</div>
{% endblock content%}

Bus_admin/templates/Bus_admin/manage_single_bus.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}
<div>
    <a href="{% url 'Bus_admin:add-single-bus' bus.id %}">Add Single Bus</a> {% for single_bus in single_buses%}
    <p>{{single_bus.bus.name}} - {{single_bus.plate_number}} - {{single_bus.bus_number}}- {{single_bus.bus_type}} - {{single_bus.bus_detail}} - {{single_bus.number_of_seats}} - <a href="{% url 'Bus_admin:update-single-bus' single_bus.id %}">Update</a> -
        <a href="{% url 'Bus_admin:delete-single-bus' single_bus.id %}">Delete</a></p>

    {%endfor%}
</div>
{% endblock content%}

Bus_admin/templates/Bus_admin/route_form.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}

<div>
    <form method="POST" action="">
        {% csrf_token %} {{form.as_p}}

        <input type="submit" value="Submit">
    </form>

</div>
{% endblock content%}

Bus_admin/templates/Bus_admin/start_home.html
<h3>

    Hello {{request.user.username}} welcome!</h3>
<h4><a href="{% url 'Bus_admin:home' request.user.id %}">Go manage your Bus</a></h4>

Bus_admin/templates/Bus_admin/update_single_bus.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}
<div>
    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <label for="bus">Bus Brand:</label><br>
            <input type="text" id="bus" name="bus" value="{{single_bus.bus.name}}" readonly>
        </div>

        <div>
            <label for="plate_number">Bus Plate Number:</label><br>
            <input type="text" id="plate_number" name="plate_number" min="1" value="{{single_bus.plate_number}}" required>
        </div>

        <div>
            <label for="bus_number">Bus Number:</label><br>
            <input type="number" id="bus_number" name="bus_number" value="{{single_bus.bus_number}}" required>
        </div>


        <div>
            <label for="bus_type">Bus Type:</label><br>
            <input type="text" id="bus_type" name="bus_type" value="{{single_bus.bus_type}}" required>
        </div>
        <div>
            <label for="bus_detail">Bus detail:</label><br>
            <input type="text" id="bus_detail" name="bus_detail" value="{{single_bus.bus_detail}}" required>
        </div>
        <div>
            <label for="number_of_seats">Number of Seat:</label><br>
            <input type="number" id="number_of_seats" name="number_of_seats" value="{{single_bus.number_of_seats}}" required>
        </div>



        <input type="submit" value="Save">

    </form>
</div>
{% endblock content%}

Bus_admin/templates/Bus_admin/update_sub_route_form.html
{% extends 'bus_admin/bus_admin_main.html'%} {% block content%}

<div>
    <form method="POST" action="">
        {% csrf_token %} {{form.as_p}}


        <input type="submit" value="Update">

    </form>
</div>
{% endblock content%}