Booker/urls.py
from django.urls import path
from . import views

app_name='Booker'
urlpatterns= [
    path('home/', views.startHome, name="booker-home"),
    path('home/<str:pk>/', views.home, name="home"),
    path('booking-request/<str:pk>/', views.bookingRequest, name="booking-request"),
    path('paid-unpaid/<str:pk>/', views.finishPaymentStatus, name="paid-unpaid"),
    path('assign-seat/<str:pk>/', views.assignSeat, name="assign-seat"), 
    path('edit-assigned-seat/<str:pk>/', views.editAssignedSeat, name="edit-assigned-seat"),
    path('manage-payment_info/<str:pk>/', views.managePaymentInformation, name="manage-payment_info"),
    path('add-payment_info/<str:pk>/', views.addPaymentInfo, name="add-payment_info"),
    path('update-payment_info/<str:pk>/', views.updatePaymentInfo, name="update-payment_info"),
    path('delete-payment_info/<str:pk>/', views.deletePaymentInfo, name="delete-payment_info"),
    
]

BusBooking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static 
from django.conf import settings
from django.views.static import serve
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('Customer.urls')),
    path('booker/', include('Booker.urls')),
    path('bus-admin/', include('Bus_admin.urls')), 
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),  
]

urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

Booker/models.py
from django.db import models
from django.contrib.auth.models import User

from System_admin.models import Bus, PaymentMethod

from Bus_admin.models import Route
from Customer.models import Booking
# Create your models here.



class PaymentInformation(models.Model):
    route = models.ForeignKey(Route, on_delete=models.CASCADE)
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.CASCADE, blank=False, null=True)
    account_holder = models.CharField(max_length=55)
    account_number = models.IntegerField()
    phone_number = models.IntegerField()
    updated = models.DateTimeField(auto_now=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.route.name)
    
class FinishPayment(models.Model):
    booking=models.OneToOneField(Booking, on_delete=models.CASCADE, primary_key=True, related_name="finishpymnt_booking")
    payment_method=models.ForeignKey(PaymentInformation, on_delete=models.CASCADE, null=True)
    paid_by=models.CharField(max_length=255, null=True)
    transaction_id=models.CharField(max_length=255, null=True, blank=True)
    screenshot= models.ImageField(null=True)
    updated=models.DateTimeField(auto_now=True, null=True)
    created=models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.paid_by
    
    
class FinishPaymentStatus(models.Model):
    fnishpayment=models.OneToOneField(FinishPayment, on_delete=models.CASCADE, primary_key=True, related_name="finishpayment_status")
    status=models.BooleanField(default=False, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    def __str__(self):
        return str(self.status)
    
    
class AssignSeat(models.Model):
     booking=models.OneToOneField(Booking, on_delete=models.CASCADE, primary_key=True, related_name="assign_seat")
     seat_number=models.CharField(max_length=20, null=True)
     updated = models.DateTimeField(auto_now=True, null=True)
     created = models.DateTimeField(auto_now_add=True, null=True)
     def __str__(self):
        return str(self.seat_number)
    

Booker/forms.py
from django.forms import ModelForm
from django.conf.urls.static import static 
from .models import PaymentInformation




     
     
class PaymentInformationForm(ModelForm):
    class Meta:
        model=PaymentInformation
        fields='__all__'
      
        

Booker/views.py
from multiprocessing import context
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from Bus_admin.models import Route, SubRoute, Seat
from Customer.models import Booking
from System_admin.models import  PaymentMethod
from .models import FinishPayment, FinishPaymentStatus, PaymentInformation, AssignSeat
from .forms import  PaymentInformationForm
from django.contrib.auth.decorators import login_required, permission_required
from Customer.decorators import allowed_users
from .decorators import admin_only
# Create your views here.

@login_required(login_url='login')
@admin_only
def startHome(request):
    context={}
    return render(request, 'Booker/start_home.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def home(request, pk):
    user = get_object_or_404(User, id=pk)
    # subroute_bus_admins=user.subroutebusadmin_set.filter()
    # subroute_bus=user.subroutebusadmin.subroute_bus.all()
    # subroute_admins=user.subrouteadmin_set.filter()
    
    subroutes=user.subroute_set.filter()
    context={'user':user, 'subroutes':subroutes}
    
    if request.user != user:
           return HttpResponse("You are not allowed here!")
    return render(request, 'Booker/home.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def bookingRequest(request, pk):
    sub_route=get_object_or_404(SubRoute, id=pk)
    bookings=sub_route.booking_set.filter().order_by('-created') 
    finish_payment=FinishPayment.objects.filter()

    context={'sub_route':sub_route, 'bookings':bookings, 'finish_payment':finish_payment}
    if request.user != sub_route.sub_route_admin: 
           return HttpResponse("You are not allowed here!")
    return render(request, 'Booker/booking_request.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def finishPaymentStatus(request, pk):
    finishpayment=get_object_or_404(FinishPayment, booking_id=pk)
    bookings=Booking.objects.filter()

    if request.method == 'POST':
        status=FinishPaymentStatus.objects.create(
        fnishpayment=finishpayment,
        status=request.POST['status'],

        )
        return redirect ('Booker:booker-home')
   
    context={'bookings':bookings, 'finishpayment':finishpayment}
    # if request.user != finishpayment.booking.hotel.admin: 
    #        return HttpResponse("You are not allowed here!")
    return render(request, 'Booker/paid_unpaid.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def assignSeat(request, pk):
    booking=get_object_or_404(Booking, id=pk)
    seats=Seat.objects.all()
    if request.method == 'POST':
        asign=AssignSeat.objects.create(
        booking=booking,
        seat_number=request.POST.get('seat_number'),
       
        )
        return redirect ('Booker:booker-home')
   
    context={'booking':booking, 'seats':seats}
    if request.user != booking.route.route_admin: 
          return HttpResponse("You are not allowed here!")

    return render(request, 'Booker/assign_seat.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def editAssignedSeat(request, pk):
    asigned=get_object_or_404(AssignSeat, booking_id=pk)
    seats=Seat.objects.all()
    if request.method == 'POST':
        asign=AssignSeat.objects.filter(booking_id=pk).update(
        booking=asigned.booking,
        seat_number=request.POST.get('seat_number'),
       
        )
        return redirect ('Booker:booker-home')   
   
    context={'asigned':asigned, 'seats':seats}
    if request.user != asigned.booking.route.route_admin: 
          return HttpResponse("You are not allowed here!")

    return render(request, 'Booker/edit_assign_seat.html', context)


    """MANAGE PAYMENT INFORMATIONS"""
@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def managePaymentInformation(request, pk):
    route=get_object_or_404(Route, id=pk)
    payment_infos=route.paymentinformation_set.all()
    
    context={'route':route, 'payment_infos':payment_infos} 
    if request.user != route.route_admin: 
        return HttpResponse("You are not allowed here!")
    return render(request, 'Booker/manage_payment_info.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def addPaymentInfo(request, pk):
    route=get_object_or_404(Route, id=pk)
    pymnt_methods=PaymentMethod.objects.all()
    if request.method=='POST':
        payment_inf=PaymentInformation.objects.create(
            route=route, 
            payment_method_id=request.POST['payment_method'], 
            account_holder=request.POST['account_holder'], 
            account_number=request.POST['account_number'], 
            phone_number=request.POST['phone_number'], 
            
        )
        return redirect('Booker:booker-home')
        
    context={ 'route':route, 'pymnt_methods':pymnt_methods}
    if request.user != route.route_admin: 
        return HttpResponse("You are not allowed here!")
    return render(request, 'Booker/add_payment_info_form.html', context)
    
@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def updatePaymentInfo(request, pk):
    payment_info=get_object_or_404(PaymentInformation, id=pk)
    pymnt_methods=PaymentMethod.objects.all()
    if request.method=='POST':
        payment_inf=PaymentInformation.objects.filter(id=pk).update(
            route=payment_info.route, 
            payment_method_id=request.POST['payment_method'], 
            account_holder=request.POST['account_holder'], 
            account_number=request.POST['account_number'], 
            phone_number=request.POST['phone_number'], 
            
        )
        return redirect('Booker:booker-home')
        
    context={'payment_info':payment_info, 'pymnt_methods':pymnt_methods}
    if request.user != payment_info.route.route_admin: 
        return HttpResponse("You are not allowed here!")
    return render(request, 'Booker/update_payment_info_form.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['booker'])
def deletePaymentInfo(request, pk):
    payment_info=get_object_or_404(PaymentInformation, id=pk)
    if request.method=='POST':
        payment_info.delete()
        return redirect('Booker:booker-home')
    
    if request.user != payment_info.route.route_admin: 
        return HttpResponse("You are not allowed here!")
    return render(request, 'Booker/delete.html', {'obj':payment_info})

Booker/templates/Booker/add_payment_info_form.html
{% extends 'booker/bookermain.html'%} {% block content%}
<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label for="hotel">Route:</label><br>
        <input type="text" id="route" name="route" value="{{route.name}} " readonly>
    </div>
    <div>
        <label for="payment_method">Payment Method:</label> <br>
        <select id="payment_method" name="payment_method">
        {% for pymnt_method in pymnt_methods %} 
  
      <option name="payment_method" value="{{pymnt_method.id}}">{{pymnt_method.name}}</option>
        {%endfor%}
        </select>
    </div>
    <div>
        <label for="account_holder">Account holder:</label><br>
        <input type="text" id="account_holder" name="account_holder" required>
    </div>
    <div>
        <label for="account_number">Account number:</label><br>
        <input type="number" id="account_number" name="account_number" required>
    </div>
    <div>
        <label for="phone_number">Phone number:</label><br>
        <input type="number" id="phone_number" name="phone_number" required>
    </div>


    <input type="submit" value="Save">

</form>

{% endblock content%}

Booker/templates/Booker/assign_seat.html
{% extends 'booker/bookermain.html'%} {% block content%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('.checkvalues').click(function() {
            var txt = "";
            $('.checkvalues:checked').each(function() {
                txt += $(this).val() + ","
            });
            txt = txt.substring(0, txt.length - 1);
            $('#txtvalues').val(txt);

        });

    });
</script>


<a href="{{request.META.HTTP_REFERER}}">Go back home</a> {%if booking.finishpymnt_booking.finishpayment_status.status is True %}
<form action="" method="POST">
    {% csrf_token %}

    <div>
        <label for="seat_number">Seat: </label> {% for seat in seats %}
        <input type="checkbox" value="{{seat.seat_no}}" class="checkvalues" class="form-control"> {%endfor%}
        <input type="text" name="seat_number" id="txtvalues" readonly>
    </div>


    <input type="submit" value="submit">


</form>
{%endif%} {%endblock content%}

Booker/templates/Booker/booking_request.html
{% extends 'booker/bookermain.html'%} {% block content%}
<div class="row mt-3">
    <div class="card shadow col-md-21">
        <!-- <div class="card-header ">
            <p class="text-primary m-0 font-weight-bold">Requested Guests</p>
        </div> -->
        <div class="card-body">

            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                <table class="table dataTable my-0" id="dataTable">
                    <thead>
                        <tr>
                            <th>Bus</th>
                            <th>Traveling Customer</th>
                            <th>Traveling Contact</th>
                            <th>Route</th>
                            <!-- <th>Travel start</th>
            <th>Travel Destination</th> -->
                            <th>Travel Date</th>
                            <th>Travel Begin Time</th>
                            <th>Requested number of seat</th>
                            <th>Total Price</th>
                            <th>Paid Through</th>
                            <th>Paid by</th>
                            <th>Transaction ID</th>
                            <th>Screenshot</th>
                            <th>Assigned Seat</th>
                            <th>Status</th>
                            <th>Assign Seat</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for booking in bookings%} {%if booking.sub_route == sub_route %}

                        <tr>
                            <td>{{booking.bus}}</td>
                            <td>{{booking.travaler_name}}</td>
                            <td>{{booking.traveler_contact}}</td>
                            <td>{{booking.route.name}}</td>
                            <!-- <td>{{booking.start}}</td>
            <td>{{booking.destination}}</td> -->
                            <td>{{booking.travel_date}}</td>
                            <td>{{booking.travel_begin_time}}</td>
                            <td>{{booking.seat_quantity}}</td>
                            <td>{% widthratio booking.seat_quantity 1 booking.route.single_seat_price %}</td>
                            <td> {{booking.finishpymnt_booking.payment_method.payment_method.name}}</td>
                            <td> {{booking.finishpymnt_booking.paid_by}}</td>
                            <td> {{booking.finishpymnt_booking.transaction_id}}</td>

                            <td>
                                {% if booking.finishpymnt_booking.screenshot%}
                                <img src="{{booking.finishpymnt_booking.screenshot.url}}" alt="screenshot" style="width: 50px; height: 50px;"> {%endif%}
                            </td>

                            <td> {{booking.assign_seat.seat_number}} </td>
                            <td>
                                {% if booking.finishpymnt_booking.booking_id == booking.id%} {%if booking.finishpymnt_booking.finishpayment_status.fnishpayment_id == booking.id%} {%if booking.finishpymnt_booking.finishpayment_status.status is True %}
                                <button class="btn btn-primary">Paid</button> {%else%}
                                <button class="btn btn-danger">NotPaid</button>{%endif%} {%else%}
                                <a href="{% url 'Booker:paid-unpaid' booking.id %}">Paid/NotPaid</a> {%endif%} {%else%} -- {%endif%}
                            </td>


                            <td>
                                {%if booking.finishpymnt_booking.finishpayment_status.status is True %}
                                <div class="d-flex gap-3 justify-content-around">
                                    {%if booking.assign_seat.booking_id != booking.id %} <a href="{% url 'Booker:assign-seat' booking.id %}">Assign Seat </a>{%else%}
                                    <button class="btn btn-success">Assigned</button><br><a href="{% url 'Booker:edit-assigned-seat' booking.assign_seat.booking_id %}">Edit</a>{%endif%}

                                </div>{%endif%}
                            </td>

                        </tr>
                        {%endif%}{%endfor%}

                    </tbody>

                </table>
            </div>

        </div>
    </div>
</div>



{%endblock content%}

Booker/templates/Booker/delete.html
{% extends 'booker/bookermain.html'%} {% block content%}
<form method="POST" action="">
    {% csrf_token%}

    <p>Are you sure you want to delete "{{obj}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>

    <input type="submit" value="Confirm">

</form>
{% endblock content%}

Booker/templates/Booker/edit_assign_seat.html
{% extends 'booker/bookermain.html'%} {% block content%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('.checkvalues').click(function() {
            var txt = "";
            $('.checkvalues:checked').each(function() {
                txt += $(this).val() + ","
            });
            txt = txt.substring(0, txt.length - 1);
            $('#txtvalues').val(txt);

        });

    });
</script>


<a href="{{request.META.HTTP_REFERER}}">Go back home</a>
<form action="" method="POST">
    {% csrf_token %}

    <div>
        <label for="seat_number">Seat: </label> {% for seat in seats %}
        <input type="checkbox" value="{{seat.seat_no}}" class="checkvalues" class="form-control"> {%endfor%}
        <input type="text" name="seat_number" id="txtvalues" value="{{asigned.seat_number}}" readonly>
    </div>


    <input type="submit" value="submit">


</form>
{%endblock content%}

Booker/templates/Booker/home.html
{% extends 'booker/bookermain.html'%} {% block content%}

<div class="container-fluid">
    <div class="d-sm-flex justify-content-between align-items-center mb-4">
        <h6 class="text-dark mb-0">Manage Your Routes</h6>
    </div>


    <div class="row mt-1 py-3 my-2">
        {% for subroute in subroutes%}
        <div class="card shadow col-lg-6 my-2 mx-1">
            <div class="card-header ">

                <h3>{{subroute.main_route.name}}</h3>
            </div>
            <div class="card-body">
                <h3>{{subroute.bus.bus.name}} - {{subroute.bus.bus_number}}</h3>


                <p><a href="{% url 'Booker:manage-payment_info' subroute.main_route.id %}">Manage Payment Information</a></p>

                {% if request.user == subroute.sub_route_admin%}
                <div>
                    <p><a href="{% url 'Booker:booking-request' subroute.id %}">Booking Request</a></p>
                </div>
                {%endif%}

            </div>
        </div>
        {%endfor%}
    </div>


</div>

{%endblock content%}

Booker/templates/Booker/manage_payment_info.html
{% extends 'booker/bookermain.html'%} {% block content%}
<div>
    <h2>{{route.name}} </h2>
    <p><a href="{% url 'Booker:add-payment_info' route.id %}">Add Payment Information</a></p>
    {% for payment_info in payment_infos %}

    <p> {{payment_info.payment_method}} -- {{payment_info.account_number}}-- {{payment_info.account_holder}}-- {{payment_info.phone_number}} -- <a href="{% url 'Booker:update-payment_info' payment_info.id %}">Edit</a> -- <a href="{% url 'Booker:delete-payment_info' payment_info.id %}">Delete</a></p>
    {%endfor%}
</div>
{% endblock content%}

Booker/templates/Booker/paid_unpaid.html
<form action="" method="POST">
    {% csrf_token %}

    <input type="radio" name="status" value="True"> : Paid
    <input type="radio" name="status" value="False"> : Notpaid

    <input type="submit" value="submit">


</form>

Booker/templates/Booker/start_home.html
<h2>

    Hello {{request.user.username}} Welcome! </h2>

<button class="btn"><a href="{% url 'Booker:home' request.user.id  %}">Go Manage your Route</a></button>

Booker/templates/Booker/update_payment_info_form.html
{% extends 'booker/bookermain.html'%} {% block content%}
<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label for="hotel">Route:</label><br>
        <input type="text" id="route" name="route" value="{{payment_info.route.name}} " readonly>
    </div>
    <div>
        <label for="hotel">Payment Method:</label><br>
        <input type="text" id="payment_method" name="payment_method" value="{{payment_info.payment_method.id}} " readonly>
    </div>

    <div>
        <label for="account_holder">Account holder:</label><br>
        <input type="text" id="account_holder" name="account_holder" value="{{payment_info.account_holder}}" required>
    </div>
    <div>
        <label for="account_number">Account number:</label><br>
        <input type="number" id="account_number" name="account_number" value="{{payment_info.account_number}}" required>
    </div>
    <div>
        <label for="phone_number">Phone number:</label><br>
        <input type="number" id="phone_number" name="phone_number" value="{{payment_info.phone_number}}" required>
    </div>


    <input type="submit" value="Update">

</form>

{% endblock content%}